packages:
  - 'packages/*'
  
# Optional: Define package relationships for better dependency resolution
catalog:
  # Shared dependencies across workspaces
  typescript: ^5.3.3
  eslint: ^8.56.0
  prettier: ^3.1.1
  
# Optional: Configure pnpm settings
settings:
  auto-install-peers: true
  dedupe-peer-dependents: true
  save-exact: false