/**
 * Git Hooks Integration
 * 
 * Integrates code review agent with Git hooks for automated reviews
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';
import { codeReviewEngine, ReviewResult, Severity } from './core-engine';

const execAsync = promisify(exec);

export interface GitHookOptions {
  lightweight?: boolean;
  analyzers?: string[];
  severityThreshold?: Severity;
  maxFiles?: number;
  timeoutMs?: number;
  bypassPatterns?: string[];
}

export interface PreCommitConfig {
  enabled: boolean;
  lightweight: boolean;
  analyzers: string[];
  severityThreshold: Severity;
  maxFiles: number;
  timeoutMs: number;
  bypassPatterns: string[];
}

export class GitHooksIntegration {
  private defaultPreCommitConfig: PreCommitConfig = {
    enabled: true,
    lightweight: true,
    analyzers: ['eslint', 'typescript', 'security'],
    severityThreshold: Severity.ERROR,
    maxFiles: 20,
    timeoutMs: 10000,
    bypassPatterns: [
      'WIP:',
      'EMERGENCY:',
      'HOTFIX:',
      '--no-verify'
    ]
  };

  /**
   * Install pre-commit hook
   */
  async installPreCommitHook(projectPath: string, options?: GitHookOptions): Promise<void> {
    const gitDir = await this.findGitDirectory(projectPath);
    const hooksDir = path.join(gitDir, 'hooks');
    const preCommitPath = path.join(hooksDir, 'pre-commit');

    // Create hooks directory if it doesn't exist
    await fs.mkdir(hooksDir, { recursive: true });

    // Generate pre-commit script
    const script = this.generatePreCommitScript(options);

    // Write the hook file
    await fs.writeFile(preCommitPath, script, { mode: 0o755 });

    console.log('✅ Pre-commit hook installed successfully');
  }

  /**
   * Generate pre-commit script
   */
  private generatePreCommitScript(options?: GitHookOptions): string {
    const config = { ...this.defaultPreCommitConfig, ...options };
    
    return `#!/bin/bash
# Code Review Agent Pre-commit Hook
# Generated by Claude Code Review Agent

set -e

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m' # No Color

echo "🔍 Running pre-commit code review..."

# Check for bypass patterns in commit message
COMMIT_MSG=$(git log -1 --pretty=%B 2>/dev/null || echo "")
BYPASS_PATTERNS=(${config.bypassPatterns.map(p => `"${p}"`).join(' ')})

for pattern in "\${BYPASS_PATTERNS[@]}"; do
  if [[ "$COMMIT_MSG" == *"$pattern"* ]]; then
    echo -e "\${YELLOW}⚠️  Bypassing pre-commit review due to: $pattern\${NC}"
    exit 0
  fi
done

# Get staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\\.(ts|tsx|js|jsx)$' || true)

if [ -z "$STAGED_FILES" ]; then
  echo "No JavaScript/TypeScript files to review"
  exit 0
fi

# Count files
FILE_COUNT=$(echo "$STAGED_FILES" | wc -l | tr -d ' ')

if [ "$FILE_COUNT" -gt ${config.maxFiles} ]; then
  echo -e "\${YELLOW}⚠️  Too many files changed ($FILE_COUNT > ${config.maxFiles}). Skipping detailed review.\${NC}"
  echo "Consider running a full review with: pnpm review"
  exit 0
fi

# Create temporary directory for staged files
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

# Copy staged files to temp directory
echo "$STAGED_FILES" | while IFS= read -r file; do
  mkdir -p "$TEMP_DIR/$(dirname "$file")"
  git show ":$file" > "$TEMP_DIR/$file"
done

# Run code review
REVIEW_OUTPUT=$(node -e "
const { codeReviewEngine } = require('${path.join(__dirname, 'index.js')}');

async function runReview() {
  const files = process.argv.slice(1);
  const result = await codeReviewEngine.review({
    targetPaths: files,
    analyzers: ${JSON.stringify(config.analyzers)},
    severityThreshold: '${config.severityThreshold}'
  });
  
  // Filter only errors for pre-commit
  const errors = result.findings.filter(f => f.severity === 'error');
  
  if (errors.length > 0) {
    console.log('\\n❌ Code review found issues:\\n');
    errors.forEach(finding => {
      console.log(\`  \${finding.file}:\${finding.line || 0} - \${finding.message}\`);
    });
    console.log('\\n💡 Fix these issues or commit with --no-verify to bypass');
    process.exit(1);
  } else {
    console.log('✅ Code review passed');
    process.exit(0);
  }
}

runReview().catch(err => {
  console.error('Code review failed:', err.message);
  process.exit(1);
});
" $TEMP_DIR/*)

# Exit with the review result
exit $?
`;
  }

  /**
   * Install post-commit hook for PR integration
   */
  async installPostCommitHook(projectPath: string): Promise<void> {
    const gitDir = await this.findGitDirectory(projectPath);
    const hooksDir = path.join(gitDir, 'hooks');
    const postCommitPath = path.join(hooksDir, 'post-commit');

    const script = `#!/bin/bash
# Code Review Agent Post-commit Hook
# Prepares data for PR review

# Store commit info for PR review
COMMIT_SHA=$(git rev-parse HEAD)
COMMIT_MSG=$(git log -1 --pretty=%B)
CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)

# Save to temporary file for PR hook
mkdir -p .git/review-data
echo "$COMMIT_SHA" > .git/review-data/latest-commit
echo "$COMMIT_MSG" > .git/review-data/latest-message
echo "$CHANGED_FILES" > .git/review-data/latest-files

exit 0
`;

    await fs.writeFile(postCommitPath, script, { mode: 0o755 });
    console.log('✅ Post-commit hook installed successfully');
  }

  /**
   * Generate GitHub PR webhook handler
   */
  async generatePRWebhookHandler(projectPath: string): Promise<string> {
    const handlerCode = `/**
 * GitHub PR Webhook Handler for Code Review
 * 
 * Add this to your server to handle PR events
 */

import { codeReviewEngine } from '@/agents/code-review-agent';
import { Octokit } from '@octokit/rest';

export async function handlePullRequestWebhook(payload: any) {
  const { action, pull_request, repository } = payload;
  
  // Only review on PR opened or synchronized
  if (!['opened', 'synchronize'].includes(action)) {
    return;
  }

  const octokit = new Octokit({
    auth: process.env.GITHUB_TOKEN
  });

  try {
    // Get PR files
    const { data: files } = await octokit.pulls.listFiles({
      owner: repository.owner.login,
      repo: repository.name,
      pull_number: pull_request.number
    });

    // Filter for reviewable files
    const reviewableFiles = files
      .filter(f => f.filename.match(/\\.(ts|tsx|js|jsx)$/))
      .map(f => f.filename);

    if (reviewableFiles.length === 0) {
      return;
    }

    // Run comprehensive review
    const result = await codeReviewEngine.review({
      targetPaths: reviewableFiles,
      severityThreshold: 'warning'
    });

    // Group findings by file
    const findingsByFile = new Map<string, any[]>();
    for (const finding of result.findings) {
      const list = findingsByFile.get(finding.file) || [];
      list.push(finding);
      findingsByFile.set(finding.file, list);
    }

    // Post review comments
    const comments = [];
    for (const [file, findings] of findingsByFile) {
      const prFile = files.find(f => f.filename === file);
      if (!prFile) continue;

      for (const finding of findings) {
        if (finding.line) {
          comments.push({
            path: file,
            line: finding.line,
            body: \`**[\${finding.analyzer}]** \${finding.message}\${
              finding.documentation ? \`\\n[📚 Documentation](\${finding.documentation})\` : ''
            }\`
          });
        }
      }
    }

    // Create review
    if (comments.length > 0) {
      await octokit.pulls.createReview({
        owner: repository.owner.login,
        repo: repository.name,
        pull_number: pull_request.number,
        body: \`## 🔍 Automated Code Review\\n\\nFound \${result.findings.length} issues across \${reviewableFiles.length} files.\\n\\n### Summary:\\n- Errors: \${result.summary.bySeverity.error || 0}\\n- Warnings: \${result.summary.bySeverity.warning || 0}\\n- Info: \${result.summary.bySeverity.info || 0}\`,
        event: result.summary.bySeverity.error > 0 ? 'REQUEST_CHANGES' : 'COMMENT',
        comments: comments.slice(0, 50) // GitHub limits comments per review
      });
    } else {
      await octokit.pulls.createReview({
        owner: repository.owner.login,
        repo: repository.name,
        pull_number: pull_request.number,
        body: '## ✅ Automated Code Review\\n\\nNo issues found! Good job! 🎉',
        event: 'APPROVE'
      });
    }
  } catch (error) {
    console.error('PR review failed:', error);
    
    // Post error comment
    await octokit.issues.createComment({
      owner: repository.owner.login,
      repo: repository.name,
      issue_number: pull_request.number,
      body: '❌ Automated code review failed. Please check the logs.'
    });
  }
}
`;

    const handlerPath = path.join(projectPath, '.claude/agents/code-review-agent/pr-webhook-handler.ts');
    await fs.writeFile(handlerPath, handlerCode);
    
    return handlerPath;
  }

  /**
   * Setup complete Git integration
   */
  async setupGitIntegration(projectPath: string, options?: GitHookOptions): Promise<void> {
    console.log('🔧 Setting up Git integration for Code Review Agent...\n');

    // Install pre-commit hook
    await this.installPreCommitHook(projectPath, options);

    // Install post-commit hook
    await this.installPostCommitHook(projectPath);

    // Generate PR webhook handler
    const handlerPath = await this.generatePRWebhookHandler(projectPath);

    // Create .gitreview config file
    await this.createGitReviewConfig(projectPath, options);

    console.log('\n✅ Git integration setup complete!');
    console.log('\nNext steps:');
    console.log('1. PR webhook handler created at:', handlerPath);
    console.log('2. Add GITHUB_TOKEN to your environment variables');
    console.log('3. Configure your GitHub webhook to call the handler');
    console.log('\nTo bypass pre-commit review, use:');
    console.log('  git commit --no-verify');
    console.log('  or prefix commit message with: WIP:, EMERGENCY:, or HOTFIX:');
  }

  /**
   * Create .gitreview configuration file
   */
  private async createGitReviewConfig(projectPath: string, options?: GitHookOptions): Promise<void> {
    const config = {
      preCommit: { ...this.defaultPreCommitConfig, ...options },
      pullRequest: {
        enabled: true,
        analyzers: ['eslint', 'typescript', 'security', 'performance', 'architecture'],
        severityThreshold: 'warning',
        postComments: true,
        requestChangesOnError: true,
        approveOnSuccess: true
      },
      bypass: {
        patterns: this.defaultPreCommitConfig.bypassPatterns,
        users: [],
        branches: ['hotfix/*', 'emergency/*']
      }
    };

    const configPath = path.join(projectPath, '.gitreview');
    await fs.writeFile(configPath, JSON.stringify(config, null, 2));

    // Add to .gitignore if not already there
    try {
      const gitignorePath = path.join(projectPath, '.gitignore');
      const gitignore = await fs.readFile(gitignorePath, 'utf-8');
      
      if (!gitignore.includes('.git/review-data')) {
        await fs.appendFile(gitignorePath, '\n# Code review data\n.git/review-data/\n');
      }
    } catch {
      // .gitignore might not exist
    }
  }

  /**
   * Find .git directory
   */
  private async findGitDirectory(startPath: string): Promise<string> {
    let currentPath = path.resolve(startPath);
    
    while (currentPath !== path.dirname(currentPath)) {
      const gitPath = path.join(currentPath, '.git');
      
      try {
        const stat = await fs.stat(gitPath);
        if (stat.isDirectory()) {
          return gitPath;
        }
      } catch {
        // Continue searching
      }
      
      currentPath = path.dirname(currentPath);
    }
    
    throw new Error('Not in a Git repository');
  }

  /**
   * Get changed files in current commit/PR
   */
  async getChangedFiles(options: { 
    staged?: boolean; 
    commit?: string; 
    branch?: string 
  } = {}): Promise<string[]> {
    let command: string;
    
    if (options.staged) {
      command = 'git diff --cached --name-only --diff-filter=ACM';
    } else if (options.commit) {
      command = `git diff-tree --no-commit-id --name-only -r ${options.commit}`;
    } else if (options.branch) {
      command = `git diff --name-only ${options.branch}...HEAD`;
    } else {
      command = 'git diff --name-only HEAD~1';
    }
    
    try {
      const { stdout } = await execAsync(command);
      return stdout.trim().split('\n').filter(f => f.length > 0);
    } catch (error) {
      console.error('Failed to get changed files:', error);
      return [];
    }
  }

  /**
   * Run review on changed files
   */
  async reviewChangedFiles(options: {
    staged?: boolean;
    commit?: string;
    branch?: string;
    analyzers?: string[];
  } = {}): Promise<ReviewResult> {
    const files = await this.getChangedFiles(options);
    const jsFiles = files.filter(f => f.match(/\.(ts|tsx|js|jsx)$/));
    
    if (jsFiles.length === 0) {
      return {
        success: true,
        findings: [],
        summary: {
          totalFindings: 0,
          byAnalyzer: {},
          bySeverity: {
            error: 0,
            warning: 0,
            info: 0,
            suggestion: 0
          },
          filesReviewed: 0,
          timeElapsed: 0
        }
      };
    }
    
    return codeReviewEngine.review({
      targetPaths: jsFiles,
      analyzers: options.analyzers
    });
  }
}

// Export singleton instance
export const gitHooksIntegration = new GitHooksIntegration();